### ISSUE TITLE
Panic on Option unwrap in skip.rs

### ISSUE THREAD

**Issue by UnlimitedCookies** [aquelemiguel/parrot#133]
## Description

While running the bot I got this error message:
```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/commands/skip.rs:64:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
[
Relevant code](https://github.com/aquelemiguel/parrot/blob/main/src/commands/skip.rs#L64)

## Expected vs. Observed

I expect it to not panic. Maybe a match needs to be used here.

## Repro Steps

I don't exactly know how I was able to get this error, but my bug report alone should be an indication that this indeed can be a `None`.

## Environment

| Key | Value |
| --- | --- |
| **Operating System** | Arch Linux|

**Comment by afonsojramos** [comment]
What version are you using @UnlimitedCookies?

@aquelemiguel are we missing some initialization in `client.rs`? This is happening here: 

```rust
pub async fn forget_skip_votes(data: &Arc<RwLock<TypeMap>>, guild_id: GuildId) {
    let mut data = data.write().await;
    let cache_map = data.get_mut::<GuildCacheMap>().unwrap();

--->let cache = cache_map.get_mut(&guild_id).unwrap();
    cache.current_skip_votes = HashSet::new();
}
```

**Comment by UnlimitedCookies** [comment]
> What version are you using @UnlimitedCookies?

I am on `v1.2.1-0-g6d35a93` of parrot
and I compiled the binary with rust `1.60.0-nightly (27f5d830e 2022-02-02)` in release mode.

**Comment by aquelemiguel** [comment]
Thank you for your report, @UnlimitedCookies. 🙂

I was able to replicate this by playing a track and just letting it finish.
For context, this is the line in question:

https://github.com/aquelemiguel/parrot/blob/6d35a93fc99941ffa7ce2801a8df2d0eab015a09/src/commands/skip.rs#L64

This unwrap is dangerous because the `GuildCacheMap` struct only has a guild ID if we had previously called `/queue` or `/skip`.
I would just propagate the error upwards and leave it to the caller to silently dismiss the error as we were discussing on #127.

**Comment by aquelemiguel** [comment]
BTW, this does not break functionality at all, but does looks bad in the terminal.
