### ISSUE TITLE
Bot is not playing track

### ISSUE THREAD

**Issue by Educorreia932** [aquelemiguel/parrot#242]
### 📝 Description

Even though not displaying any error and fetching the query results correctly, the bot is not playing any kind of track.

### 🪜 Reproduction Steps

1. Use `/play` command 
2. Bot is summoned, but no track is played (as stated by `/np` command as well)

### ℹ Environment / Computer Info

- **Parrot version**:  `1.6.0`
- **Operating System**:  `Windows 10`

Using the Docker image doesn't seem to have any problems, this happened while testing the bot locally.

### 📸 Screenshots

![image](https://github.com/aquelemiguel/parrot/assets/44172778/6aa10df1-ffdd-44d8-8e11-0efb3c58756a)

**Comment by afonsojramos** [comment]
> Using the Docker image doesn't seem to have any problems, this happened while testing the bot locally.

Having this in mind, my guess is that it is either yt-dlp or ffmpeg interfering in some way. As those are the things that sort of work outside our dependencies.

**Comment by lucawen** [comment]
Did you managed to fix it ?

**Comment by lordzsolt** [comment]
@lucawen I had the same issue, upgrading yt-dlp version fixed it. (I had a ~4 month old yt-dlp)

**Comment by Educorreia932** [comment]
I tested in Linux afterwards and it also worked, so it might just have been the `yt-dlp` version
As such, I will close this issue for the moment

**Comment by lordzsolt** [comment]
Edit: Actually... 
I looked at the error log, I see the following error when attempting to download the metadata:

```
Application error: WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
```

Which is an issue reported on yt-dlp: https://github.com/yt-dlp/yt-dlp/issues/7143
However, strangely if I run yt-dlp manually, it successfully downloads the file.
And right after, it seems to get the correct metadata.

My guess is that somehow this error is intercepted by parrot, and song in the stdout is ignored.
And since all metadata is fetched from Youtube, nothing gets played.

I tried disabling the metadata entirely, however still nothing gets played.

Unfortunately, I don't know the project well enough to debug further.

@afonsojramos Any ideas?

**Comment by houseofbugs** [comment]
I'm getting this as well and updating to a new yt-dlp was the fix. I logged into the container console and ran `pip install -U yt-dlp`

**Comment by joao-conde** [comment]
> I'm getting this as well and updating to a new yt-dlp was the fix. I logged into the container console and ran `pip install -U yt-dlp`

We already do that in the container, did it find a new version? Did it really updated?
https://github.com/aquelemiguel/parrot/blob/main/Dockerfile#L25

**Comment by houseofbugs** [comment]
Yeah my container was on 2023.03.06 of the yt-dlp and now it's on 2023.11.16

**Comment by joao-conde** [comment]
If you remove cache and rebuild the container with this same docker image, is it still the case?

**Comment by houseofbugs** [comment]
Yessir. I already tried that. Did it on multiple machines as well. I'm using the official docker install.
